# This file is part of IVRE.
# Copyright 2011 - 2026 Pierre LALET <pierre@droids-corp.org>
#
# IVRE is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# IVRE is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with IVRE. If not, see <http://www.gnu.org/licenses/>.

name: MongoDB tests

on: [push, pull_request]

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'master')}}

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        # https://www.mongodb.com/docs/languages/python/pymongo-driver/current/compatibility/
        python-version: ['3.11', '3.12']
        mongodb-version: ['5.0', '6.0', '7.0', '8.0']

    steps:

    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.1
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: pip install -r requirements-mongo.txt

    - name: Install MongoDB tools (mongodump)
      if: ${{ matrix.mongodb-version == '5.0' && matrix.python-version == '3.12' }}
      run: |
          wget -qO- https://www.mongodb.org/static/pgp/server-8.0.asc | sudo tee /etc/apt/trusted.gpg.d/server-8.0.asc > /dev/null
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list > /dev/null
          sudo apt-get -q update
          sudo apt-get -qy install mongodb-org-tools

    - name: Install IVRE
      uses: ./.github/actions/install

    - run: python -c 'import json, pymongo; print(json.dumps(pymongo.MongoClient().server_info(), indent=4))'

    - name: Initialize IVRE databases
      run: for cli in ipinfo scancli view flowcli; do ivre $cli --init < /dev/null; done

    - run: cd tests && python tests.py
      env:
        CI: true
        DB: mongo

    - name: Create MongoDB dump for Elasticsearch tests
      if: ${{ matrix.mongodb-version == '5.0' && matrix.python-version == '3.12' }}
      run: |
          rm -rf ./backup/ && mkdir ./backup/
          mongodump --db=ivre --out=./backup/
          mv ./backup/ivre/*.bson ./backup/
          tar jcf ./backup_nmap_passive.tar.bz2 ./backup/{hosts,passive}.bson

    - name: Archive MongoDB dump artifacts
      if: ${{ matrix.mongodb-version == '5.0' && matrix.python-version == '3.12' }}
      uses: actions/upload-artifact@v4
      with:
        name: backup_nmap_passive
        path: ./backup_nmap_passive.tar.bz2

    - run: cat /tmp/webserver.log
      if: failure()
